### ISSUE TITLE
No support for openSUSE Leap

### ISSUE THREAD

**Issue by WildCoder** [Connor-GH/fetchme#4]
`I have NO Idea what
distro you are using
but here is Tux.`
opensuse uses the zypper package manager.
I'm not sure if it's the best way but I would count packages like this: `zypper search -i | grep "^i+" | wc -l`

**Comment by Connor-GH** [comment]
This is very helpful. Thank you. (BTW new distro requests should be made like this)

**Comment by Connor-GH** [comment]
OpenSUSE is added now.
